import rubick.schemas.cinder
import rubick.schemas.glance_api
import rubick.schemas.glance_registry
import rubick.schemas.keystone
import rubick.schemas.neutron_server
import rubick.schemas.neutron_dhcp_agent
import rubick.schemas.neutron_l3_agent
import rubick.schemas.neutron_metadata_agent
import rubick.schemas.neutron_openvswitch_agent
import rubick.schemas.nova
import rubick.schemas.swift_account_server
import rubick.schemas.swift_container_server
import rubick.schemas.swift_object_server
import rubick.schemas.swift_proxy_server
import rubick.schemas.rabbitmq
